# -*- coding: utf-8 -*-
"""parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J1ciVypGZknecx7CMFs1jhAMJRU8ZT6l
"""

pip install pypdf2

import PyPDF2

pdfFileObj = open('/resume.pdf', 'rb')

# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

pageobj = pdfReader.getPage(0)

print(pageobj.extractText())

text=pageobj.extractText()

import re

EMAIL_REG = re.compile(r'[a-z0-9\.\-+_]+@[a-z0-9\.\-+_]+\.[a-z]+')

re.findall(EMAIL_REG, text)

ph = re.compile(r"\d\d\d\d\d\d\d\d\d\d\d\d")

a=re.findall(ph,text)
if len(a)==0:
  ph = re.compile(r"\d\d\d\d\d\d\d\d\d\d")
  a=re.findall(ph,text)
print(a)

import csv

import nltk
nltk.download('punkt')

from nltk import word_tokenize

tk=word_tokenize(text)

l=[]
with open('/skills.csv', 'r') as f:
  reader = csv.reader(f)
  for j in text:
    if j in reader:
      l.append(j)